---
- name: Check ROS and upgrade if needed
  hosts: mikrotik_test
  gather_facts: no
  strategy: free
  vars:
# I recommend setting the timeout to two minutes or even longer depending on how long it takes the device to pull the file.
    ansible_command_timeout: 120
    ansible_ssh_user: ansible

  roles:
    - mtk-ros-upgrade
